version: '3.8'

services:
  coturn:
    image: coturn/coturn:latest
    container_name: coturn-server
    restart: always
    network_mode: "host"
    volumes:
      - ./turnserver.conf:/etc/coturn/turnserver.conf
